Add deployment.yaml and service.yaml -> Update CI workflow with add tag for application

diff --git a/.github/workflows/ci_workflows.yml b/.github/workflows/ci_workflows.yml
--- a/.github/workflows/ci_workflows.yml
+++ b/.github/workflows/ci_workflows.yml
@@ -3,11 +3,13 @@ name: Python application CI
 on:
   push:
     branches: [ "main" ]
+    tags:
+      -"v*"
   pull_request:
     branches: [ "main" ]
 
 permissions:
-  contents: read
+  contents: write
   packages: write
 
 jobs:
@@ -16,6 +18,8 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
       - name: Login to Docker Hub
         uses: docker/login-action@v4
@@ -37,3 +41,24 @@ jobs:
           tags: |
             ${{ vars.DOCKERHUB_USERNAME }}/py_app:latest
             ${{ vars.DOCKERHUB_USERNAME }}/py_app:${{ github.sha }}
+
+      - name: Update image tag in K8s manifest
+        run: |
+          if [ -f k8s/deployment.yaml ]; then
+            sed -i "s|image: ${{ vars.DOCKERHUB_USERNAME }}/py_app:.*|image: ${{ vars.DOCKERHUB_USERNAME }}/py_app:${{ github.sha }}|g" k8s/deployment.yaml
+            
+            git config --global user.name 'GitHub Actions Bot'
+            git config --global user.email 'actions@github.com'
+            
+            # Kiểm tra xem có thay đổi thực sự không trước khi commit
+            git add k8s/deployment.yaml
+            if git diff-index --quiet HEAD; then
+              echo "No changes to commit"
+            else
+              git commit -m "Auto-update image tag to ${{ github.sha }} [skip ci]"
+              git push
+            fi
+          else
+            echo "Error: k8s/deployment.yaml not found!"
+            exit 1
+          fi
